name: Web Export

on:
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: .

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache Godot executable
        uses: actions/cache@v3
        with:
          path: godot/Godot_v4.3-stable_linux.x86_64
          key: godot-4.3-linux-${{ runner.os }}
          restore-keys: godot-4.3-linux-

      - name: Download Godot if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p godot
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v4.3-stable_linux.x86_64

      - name: Move Godot to PATH
        run: sudo mv godot/Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot

      - name: Move Export Templates
        run: |
          sudo mkdir -p /home/runner/.local/share/godot/export_templates/4.3.stable
          sudo chmod +x /home/runner/.local/share/godot/export_templates/4.3.stable
          sudo cp $WORKING_DIRECTORY/build/export_templates/4.3.stable/* /home/runner/.local/share/godot/export_templates/4.3.stable

      - name: Create export directory
        run: mkdir -p $WORKING_DIRECTORY/build/web

      - name: Godot HTML5 export
        run: |
          godot --export-release --headless "HTML5" $WORKING_DIRECTORY/build/web/index.html
