name: Web Export

on:
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: .

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download and install Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_linux_headless.64.zip
          unzip Godot_v4.3-stable_linux_headless.64.zip -d godot
          mv godot/Godot_v4.3-stable_linux_headless.64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot

      - name: Create export directory
        run: mkdir -p $WORKING_DIRECTORY/build/web

      - name: Godot HTML5 export
        run: |
          godot --export "HTML5" $WORKING_DIRECTORY/build/web/index.html
