name: Web Export

on:
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: .

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir -p $WORKING_DIRECTORY/build/web

      - name: Godot HTML5 export
        run: |
          godot --export "HTML5" $WORKING_DIRECTORY/build/web/index.html
